[package]
name = "locat"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = "0.29"
thiserror = "1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
